-- MySQL Script generated by MySQL Workbench
-- 08/26/17 00:35:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mi151_00_master_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mi151_00_master_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mi151_00_master_db` DEFAULT CHARACTER SET utf8 ;
USE `mi151_00_master_db` ;

-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `employee_type` VARCHAR(45) NULL,
  `employee_fname` VARCHAR(45) NULL,
  `employee_mname` VARCHAR(45) NULL,
  `employee_lname` VARCHAR(45) NULL,
  `employee_contact_number` BIGINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`template` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `template_type` VARCHAR(45) NULL,
  `template_description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_type` VARCHAR(45) NULL,
  `customer_email` VARCHAR(45) NULL,
  `customer_fname` VARCHAR(45) NULL,
  `customer_mname` VARCHAR(45) NULL,
  `customer_lname` VARCHAR(45) NULL,
  `customer_contact_number` BIGINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`email` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email_date` DATE NULL,
  `email_recipient` VARCHAR(45) NULL,
  `email_content` VARCHAR(1000) NULL,
  `email_template` VARCHAR(45) NULL,
  `email_status` VARCHAR(45) NULL,
  `template_id` INT NOT NULL,
  `recipient_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_email_template1_idx` (`template_id` ASC),
  INDEX `fk_email_recipient1_idx` (`recipient_id` ASC),
  CONSTRAINT `fk_email_template1`
    FOREIGN KEY (`template_id`)
    REFERENCES `mi151_00_master_db`.`template` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_email_recipient1`
    FOREIGN KEY (`recipient_id`)
    REFERENCES `mi151_00_master_db`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`customer_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`customer_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_history_checkin` VARCHAR(45) NULL,
  `customer_history_checkout` VARCHAR(45) NULL,
  `customer_history_numberdays` VARCHAR(45) NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_customer_history_customer1_idx` (`customer_id` ASC),
  CONSTRAINT `fk_customer_history_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mi151_00_master_db`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`Existing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`Existing` (
  `customer_ID` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`customer_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`webvisit_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`webvisit_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `wvh_date` DATE NULL,
  `wvh_time` DATETIME NULL,
  `wvh_ip_address` VARCHAR(20) NULL,
  `wvh_url` VARCHAR(100) NULL,
  `wvh_cookie_information` VARCHAR(45) NULL,
  `recipient_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_webvisit_history_recipient1_idx` (`recipient_id` ASC),
  CONSTRAINT `fk_webvisit_history_recipient1`
    FOREIGN KEY (`recipient_id`)
    REFERENCES `mi151_00_master_db`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `event_date_created` DATETIME NULL,
  `event_description` VARCHAR(400) NULL,
  `event_start_date` DATE NULL,
  `event_end_date` DATE NULL,
  `marketeer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_event_marketeer1_idx` (`marketeer_id` ASC),
  CONSTRAINT `fk_event_marketeer1`
    FOREIGN KEY (`marketeer_id`)
    REFERENCES `mi151_00_master_db`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`preference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`preference` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `preference_category` VARCHAR(45) NULL,
  `preference_description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`activity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `activity_status` VARCHAR(45) NULL,
  `activity_description` VARCHAR(45) NULL,
  `email_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_activity_email1_idx` (`email_id` ASC),
  CONSTRAINT `fk_activity_email1`
    FOREIGN KEY (`email_id`)
    REFERENCES `mi151_00_master_db`.`email` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`email_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`email_event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `event_id` INT NOT NULL,
  `email_id` INT NOT NULL,
  INDEX `fk_event_has_email_email1_idx` (`email_id` ASC),
  INDEX `fk_event_has_email_event1_idx` (`event_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_event_has_email_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `mi151_00_master_db`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_has_email_email1`
    FOREIGN KEY (`email_id`)
    REFERENCES `mi151_00_master_db`.`email` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`customer_preference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`customer_preference` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `recipient_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_preference_has_recipient_recipient1_idx` (`recipient_id` ASC),
  INDEX `fk_preference_has_recipient_preference1_idx` (`customer_id` ASC),
  CONSTRAINT `fk_preference_has_recipient_preference1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mi151_00_master_db`.`preference` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preference_has_recipient_recipient1`
    FOREIGN KEY (`recipient_id`)
    REFERENCES `mi151_00_master_db`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`guest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`guest` (
  `guest_id` INT NOT NULL,
  `guest_name` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`guest_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`room` (
  `room_id` INT NOT NULL,
  `room_type` VARCHAR(45) NOT NULL,
  `room_loc` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`room_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`department` (
  `dept_id` INT NOT NULL,
  `dept_name` VARCHAR(45) NOT NULL,
  `dept_description` TEXT NOT NULL,
  PRIMARY KEY (`dept_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`employee1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`employee1` (
  `emp_id` INT NOT NULL,
  `dept_id` INT NOT NULL,
  `emp_name` VARCHAR(120) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`emp_id`, `dept_id`),
  INDEX `fk_employee_department1_idx` (`dept_id` ASC),
  CONSTRAINT `fk_employee_department1`
    FOREIGN KEY (`dept_id`)
    REFERENCES `mi151_00_master_db`.`department` (`dept_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`ticket` (
  `ticket_id` INT NOT NULL,
  `guest_id` INT NOT NULL,
  `room_id` INT NOT NULL,
  `emp_create_id` INT NOT NULL,
  `date_created` DATE NOT NULL,
  PRIMARY KEY (`ticket_id`, `guest_id`, `room_id`, `emp_create_id`),
  INDEX `fk_ticket_guest_idx` (`guest_id` ASC),
  INDEX `fk_ticket_room1_idx` (`room_id` ASC),
  INDEX `fk_ticket_employee1_idx` (`emp_create_id` ASC),
  CONSTRAINT `fk_ticket_guest`
    FOREIGN KEY (`guest_id`)
    REFERENCES `mi151_00_master_db`.`guest` (`guest_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_room1`
    FOREIGN KEY (`room_id`)
    REFERENCES `mi151_00_master_db`.`room` (`room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_employee1`
    FOREIGN KEY (`emp_create_id`)
    REFERENCES `mi151_00_master_db`.`employee1` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`category` (
  `category_id` INT NOT NULL,
  `category_name` VARCHAR(45) NOT NULL,
  `category_desc` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`ticket_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`ticket_details` (
  `ticket_det_id` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `time_start` TIMESTAMP NOT NULL,
  `time_end` TIMESTAMP NULL,
  `desc` TEXT NULL,
  `emp_resp_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `ticket_id` INT NOT NULL,
  `dept_resp_id` INT NOT NULL,
  PRIMARY KEY (`ticket_det_id`, `emp_resp_id`, `category_id`, `ticket_id`, `dept_resp_id`),
  INDEX `fk_ticket_details_employee1_idx` (`emp_resp_id` ASC),
  INDEX `fk_ticket_details_category1_idx` (`category_id` ASC),
  INDEX `fk_ticket_details_ticket1_idx` (`ticket_id` ASC),
  INDEX `fk_ticket_details_department1_idx` (`dept_resp_id` ASC),
  CONSTRAINT `fk_ticket_details_employee1`
    FOREIGN KEY (`emp_resp_id`)
    REFERENCES `mi151_00_master_db`.`employee1` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_details_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mi151_00_master_db`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_details_ticket1`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `mi151_00_master_db`.`ticket` (`ticket_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_details_department1`
    FOREIGN KEY (`dept_resp_id`)
    REFERENCES `mi151_00_master_db`.`department` (`dept_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`landmark`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`landmark` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `landmark_name` VARCHAR(45) NULL,
  `landmark_address` VARCHAR(45) NULL,
  `landmark_distance_from_user` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `user_surname` VARCHAR(45) NOT NULL,
  `user_email` VARCHAR(45) NULL,
  `user_phone` INT NULL,
  `landmark_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_landmark1_idx` (`landmark_id` ASC),
  CONSTRAINT `fk_user_landmark1`
    FOREIGN KEY (`landmark_id`)
    REFERENCES `mi151_00_master_db`.`landmark` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`chat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `user2_name` VARCHAR(45) NOT NULL,
  `time` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_chat_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_chat_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mi151_00_master_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`reply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`reply` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reply_text` VARCHAR(45) NULL,
  `time` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_reply_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_reply_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mi151_00_master_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `admin_name` VARCHAR(45) NULL,
  `admin_surname` VARCHAR(45) NULL,
  `admin_contact_num` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_name` VARCHAR(45) NOT NULL,
  `date_created` DATE NULL,
  `user_id` INT NOT NULL,
  `admin_id` INT NOT NULL,
  PRIMARY KEY (`id`, `admin_id`),
  INDEX `fk_account_user1_idx` (`user_id` ASC),
  INDEX `fk_account_admin1_idx` (`admin_id` ASC),
  CONSTRAINT `fk_account_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mi151_00_master_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_admin1`
    FOREIGN KEY (`admin_id`)
    REFERENCES `mi151_00_master_db`.`admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`feedback` (
  `id` INT NOT NULL,
  `feedback_rating` VARCHAR(45) NULL,
  `feedback_comment` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  `admin_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_feedback_user1_idx` (`user_id` ASC),
  INDEX `fk_feedback_admin1_idx` (`admin_id` ASC),
  CONSTRAINT `fk_feedback_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mi151_00_master_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_feedback_admin1`
    FOREIGN KEY (`admin_id`)
    REFERENCES `mi151_00_master_db`.`admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`schedule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `conference_name` VARCHAR(45) NOT NULL,
  `conference_speaker` VARCHAR(45) NOT NULL,
  `conference_date` DATE NULL,
  `conference_time` VARCHAR(45) NULL,
  `conference_venue` VARCHAR(45) NULL,
  `admin_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_schedule_admin1_idx` (`admin_id` ASC),
  CONSTRAINT `fk_schedule_admin1`
    FOREIGN KEY (`admin_id`)
    REFERENCES `mi151_00_master_db`.`admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`chat_has_reply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`chat_has_reply` (
  `chat_id` INT NOT NULL,
  `reply_id` INT NOT NULL,
  `reply_user_id` INT NOT NULL,
  PRIMARY KEY (`chat_id`, `reply_id`, `reply_user_id`),
  INDEX `fk_chat_has_reply_reply1_idx` (`reply_id` ASC, `reply_user_id` ASC),
  INDEX `fk_chat_has_reply_chat1_idx` (`chat_id` ASC),
  CONSTRAINT `fk_chat_has_reply_chat1`
    FOREIGN KEY (`chat_id`)
    REFERENCES `mi151_00_master_db`.`chat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chat_has_reply_reply1`
    FOREIGN KEY (`reply_id` , `reply_user_id`)
    REFERENCES `mi151_00_master_db`.`reply` (`id` , `user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`user_has_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`user_has_schedule` (
  `user_id` INT NOT NULL,
  `schedule_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `schedule_id`),
  INDEX `fk_user_has_schedule_schedule1_idx` (`schedule_id` ASC),
  INDEX `fk_user_has_schedule_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_schedule_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mi151_00_master_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_schedule_schedule1`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `mi151_00_master_db`.`schedule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`employee2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`employee2` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `employee_lastname` VARCHAR(45) NULL,
  `employee_firstname` VARCHAR(45) NULL,
  `employee_number` INT NULL,
  `employee_email` VARCHAR(45) NULL,
  `employee_occupation` VARCHAR(45) NULL,
  `employee_user_type` VARCHAR(45) BINARY NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`schedule1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`schedule1` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `schudule_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`checklist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`checklist` (
  `id` INT NOT NULL,
  `checklist_equipment` VARCHAR(45) NULL,
  `checklist_quantity_on_hand` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`facility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`facility` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `facility_type` VARCHAR(45) NULL,
  `facility_status` VARCHAR(45) NULL,
  `facility_qrcode` VARCHAR(45) NULL,
  `checklist_id` INT NOT NULL,
  PRIMARY KEY (`id`, `checklist_id`),
  INDEX `fk_facility_checklist1_idx` (`checklist_id` ASC),
  CONSTRAINT `fk_facility_checklist1`
    FOREIGN KEY (`checklist_id`)
    REFERENCES `mi151_00_master_db`.`checklist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`employee_has_facility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`employee_has_facility` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NULL,
  `facility_id` INT NULL,
  INDEX `fk_employee_has_facility_facility1_idx` (`facility_id` ASC),
  INDEX `fk_employee_has_facility_employee_idx` (`employee_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_employee_has_facility_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mi151_00_master_db`.`employee2` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_has_facility_facility1`
    FOREIGN KEY (`facility_id`)
    REFERENCES `mi151_00_master_db`.`facility` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`employee_has_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`employee_has_schedule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NULL,
  `schedule_id` INT NULL,
  INDEX `fk_employee_has_schedule_schedule1_idx` (`schedule_id` ASC),
  INDEX `fk_employee_has_schedule_employee1_idx` (`employee_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_employee_has_schedule_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mi151_00_master_db`.`employee2` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_has_schedule_schedule1`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `mi151_00_master_db`.`schedule1` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`schedule_has_facility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`schedule_has_facility` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `schedule_id` INT NULL,
  `facility_id` INT NULL,
  `facility_checklist_id` INT NULL,
  INDEX `fk_schedule_has_facility_facility1_idx` (`facility_id` ASC, `facility_checklist_id` ASC),
  INDEX `fk_schedule_has_facility_schedule1_idx` (`schedule_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_schedule_has_facility_schedule1`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `mi151_00_master_db`.`schedule1` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_schedule_has_facility_facility1`
    FOREIGN KEY (`facility_id` , `facility_checklist_id`)
    REFERENCES `mi151_00_master_db`.`facility` (`id` , `checklist_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`checklist_template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`checklist_template` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `checklist_template_type` VARCHAR(10) NULL,
  `checklist_template_equipment` VARCHAR(45) NULL,
  `checklist_template_temperature` VARCHAR(45) NULL,
  `checklist_template_equipment_number` INT NULL,
  `checklist_template_equipment_description` VARCHAR(60) NULL,
  `checklist_id` INT NOT NULL,
  PRIMARY KEY (`id`, `checklist_id`),
  INDEX `fk_checklist_template_checklist1_idx` (`checklist_id` ASC),
  CONSTRAINT `fk_checklist_template_checklist1`
    FOREIGN KEY (`checklist_id`)
    REFERENCES `mi151_00_master_db`.`checklist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`hotel guest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`hotel guest` (
  `id` INT NOT NULL,
  `guest_lastname` VARCHAR(45) NULL,
  `guest_firstname` VARCHAR(45) NULL,
  `guest_contactno` VARCHAR(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`employee3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`employee3` (
  `id` INT NOT NULL,
  `servEmployee_lname` VARCHAR(45) NULL,
  `servEmployee_fname` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`service request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`service request` (
  `id` INT NOT NULL,
  `request_title` VARCHAR(45) NULL,
  `service_details` VARCHAR(45) NULL,
  `room_no` VARCHAR(20) NULL,
  `request_status` VARCHAR(20) NULL,
  `date` DATETIME NULL,
  `hotel guest_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_service request_hotel guest_idx` (`hotel guest_id` ASC),
  INDEX `fk_service request_employee1_idx` (`employee_id` ASC),
  CONSTRAINT `fk_service request_hotel guest`
    FOREIGN KEY (`hotel guest_id`)
    REFERENCES `mi151_00_master_db`.`hotel guest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service request_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mi151_00_master_db`.`employee3` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`room1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`room1` (
  `id` INT NOT NULL,
  `room_type` VARCHAR(45) NULL,
  `hotel guest_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_room_hotel guest1_idx` (`hotel guest_id` ASC),
  CONSTRAINT `fk_room_hotel guest1`
    FOREIGN KEY (`hotel guest_id`)
    REFERENCES `mi151_00_master_db`.`hotel guest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`customerservicedept`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`customerservicedept` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`customerservicedept_has_employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`customerservicedept_has_employee` (
  `customerservicedept_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`customerservicedept_id`, `employee_id`),
  INDEX `fk_customerservicedept_has_employee_employee1_idx` (`employee_id` ASC),
  INDEX `fk_customerservicedept_has_employee_customerservicedept1_idx` (`customerservicedept_id` ASC),
  CONSTRAINT `fk_customerservicedept_has_employee_customerservicedept1`
    FOREIGN KEY (`customerservicedept_id`)
    REFERENCES `mi151_00_master_db`.`customerservicedept` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customerservicedept_has_employee_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mi151_00_master_db`.`employee3` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`room_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`room_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `room_type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`room2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`room2` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `room_type_id` INT NOT NULL,
  `room_qr` BLOB NULL,
  PRIMARY KEY (`id`, `room_type_id`),
  INDEX `fk_room_room_type_idx` (`room_type_id` ASC),
  CONSTRAINT `fk_room_room_type`
    FOREIGN KEY (`room_type_id`)
    REFERENCES `mi151_00_master_db`.`room_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`employee4`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`employee4` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `employee_fname` VARCHAR(45) NULL,
  `employee_lname` VARCHAR(45) NULL,
  `employee_mi` VARCHAR(3) NULL,
  `employee_position` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`housekeeping_log_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`housekeeping_log_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `housekeeping_log_details_checklist` VARCHAR(45) NULL,
  `housekeeping_log_details_status` VARCHAR(45) NULL,
  `housekeeping_log_details_timecompleted` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`housekeeping_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`housekeeping_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `room_id` INT NOT NULL,
  `room_room_type_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  `housekeeping_log_status` VARCHAR(45) NULL,
  `housekeeping_log_timein` DATETIME NULL,
  `housekeeping_log_timeout` DATETIME NULL,
  `cleaning_status` VARCHAR(45) NULL,
  `inspected_by_employee_id` INT NULL,
  `inspection_status` VARCHAR(45) NULL,
  `housekeeping_log_details_id` INT NOT NULL,
  PRIMARY KEY (`id`, `room_id`, `room_room_type_id`, `employee_id`, `housekeeping_log_details_id`),
  INDEX `fk_room_has_employee_employee1_idx` (`employee_id` ASC),
  INDEX `fk_room_has_employee_room1_idx` (`room_id` ASC, `room_room_type_id` ASC),
  INDEX `fk_housekeeping_log_housekeeping_log_details1_idx` (`housekeeping_log_details_id` ASC),
  CONSTRAINT `fk_room_has_employee_room1`
    FOREIGN KEY (`room_id` , `room_room_type_id`)
    REFERENCES `mi151_00_master_db`.`room2` (`id` , `room_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room_has_employee_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mi151_00_master_db`.`employee4` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_housekeeping_log_housekeeping_log_details1`
    FOREIGN KEY (`housekeeping_log_details_id`)
    REFERENCES `mi151_00_master_db`.`housekeeping_log_details` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`checklist_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`checklist_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `checklist_category_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`checklist_ref`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`checklist_ref` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `checklist_description` VARCHAR(60) NULL,
  `checklist_category_id` INT NOT NULL,
  PRIMARY KEY (`id`, `checklist_category_id`),
  INDEX `fk_checklist_ref_checklist_category1_idx` (`checklist_category_id` ASC),
  CONSTRAINT `fk_checklist_ref_checklist_category1`
    FOREIGN KEY (`checklist_category_id`)
    REFERENCES `mi151_00_master_db`.`checklist_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`checklist_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`checklist_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `checklist_ref_id` INT NOT NULL,
  `room_type_id` INT NOT NULL,
  PRIMARY KEY (`id`, `checklist_ref_id`, `room_type_id`),
  INDEX `fk_checklist_ref_has_room_type_room_type1_idx` (`room_type_id` ASC),
  INDEX `fk_checklist_ref_has_room_type_checklist_ref1_idx` (`checklist_ref_id` ASC),
  CONSTRAINT `fk_checklist_ref_has_room_type_checklist_ref1`
    FOREIGN KEY (`checklist_ref_id`)
    REFERENCES `mi151_00_master_db`.`checklist_ref` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_checklist_ref_has_room_type_room_type1`
    FOREIGN KEY (`room_type_id`)
    REFERENCES `mi151_00_master_db`.`room_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`customer1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`customer1` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`room3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`room3` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `room_type` VARCHAR(45) NOT NULL,
  `room_loc` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`check_in`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`check_in` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `room_id` INT NOT NULL,
  `check_in` DATE NOT NULL,
  `check_out` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ticket_room1_idx` (`room_id` ASC),
  INDEX `fk_ticket_customer1_idx` (`customer_id` ASC),
  CONSTRAINT `fk_ticket_room1`
    FOREIGN KEY (`room_id`)
    REFERENCES `mi151_00_master_db`.`room3` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mi151_00_master_db`.`customer1` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`department1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`department1` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dept_name` VARCHAR(45) NOT NULL,
  `dept_description` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`employee5`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`employee5` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `department_id` INT NOT NULL,
  `fname` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `supervisor` INT NOT NULL,
  `sched_start` TIME NOT NULL,
  `sched_end` TIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employee_department1_idx` (`department_id` ASC),
  INDEX `fk_employee_employee1_idx` (`supervisor` ASC),
  CONSTRAINT `fk_employee_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `mi151_00_master_db`.`department1` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_employee1`
    FOREIGN KEY (`supervisor`)
    REFERENCES `mi151_00_master_db`.`employee5` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`category1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`category1` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `department_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `desc` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_category_department1_idx` (`department_id` ASC),
  CONSTRAINT `fk_category_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `mi151_00_master_db`.`department1` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`ticket1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`ticket1` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  `time_start` TIMESTAMP NOT NULL,
  `time_end` TIMESTAMP NULL,
  `time_alloted` TIME NOT NULL,
  `escalation_level` INT NOT NULL,
  `desc` TEXT NOT NULL,
  `check_in_id` INT NOT NULL,
  `emp_repond_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `emp_create_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ticket_check_in1_idx` (`check_in_id` ASC),
  INDEX `fk_ticket_employee1_idx` (`emp_repond_id` ASC),
  INDEX `fk_ticket_category1_idx` (`category_id` ASC),
  INDEX `fk_ticket_employee2_idx` (`emp_create_id` ASC),
  CONSTRAINT `fk_ticket_check_in1`
    FOREIGN KEY (`check_in_id`)
    REFERENCES `mi151_00_master_db`.`check_in` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_employee1`
    FOREIGN KEY (`emp_repond_id`)
    REFERENCES `mi151_00_master_db`.`employee5` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mi151_00_master_db`.`category1` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_employee2`
    FOREIGN KEY (`emp_create_id`)
    REFERENCES `mi151_00_master_db`.`employee5` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi151_00_master_db`.`transcript`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi151_00_master_db`.`transcript` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ticket_id` INT NOT NULL,
  `description` TEXT NOT NULL,
  `time` TIMESTAMP NOT NULL,
  `by_employee` INT NOT NULL,
  `current_emp_resp` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transcript_ticket1_idx` (`ticket_id` ASC),
  INDEX `fk_transcript_employee1_idx` (`by_employee` ASC),
  INDEX `fk_transcript_employee2_idx` (`current_emp_resp` ASC),
  CONSTRAINT `fk_transcript_ticket1`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `mi151_00_master_db`.`ticket1` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transcript_employee1`
    FOREIGN KEY (`by_employee`)
    REFERENCES `mi151_00_master_db`.`employee5` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transcript_employee2`
    FOREIGN KEY (`current_emp_resp`)
    REFERENCES `mi151_00_master_db`.`employee5` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
